# Generated by Django 3.0.6 on 2021-07-08 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Balance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='balance',
        ),
        migrations.AddField(
            model_name='balance',
            name='asset',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='balance',
            name='btc',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='balance',
            name='capital',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='balance',
            name='profit',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='balance',
            name='usd',
            field=models.FloatField(default=0.0),
        ),
    ]
