# Generated by Django 4.0.3 on 2022-04-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Balance', '0003_auto_20210715_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
