# Generated by Django 3.0.6 on 2021-07-06 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balance',
            old_name='user',
            new_name='name',
        ),
    ]
