# Generated by Django 3.0.6 on 2021-07-06 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210706_1003'),
    ]

    operations = [
        migrations.DeleteModel(
            name='balance',
        ),
    ]
